export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_RESPONSE = 'GET_PROFILE_RESPONSE'
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_RESPONSE = 'UPDATE_PROFILE_RESPONSE'
