export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE'
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_RESPONSE = 'DELETE_USER_RESPONSE'
